### ISSUE TITLE
请教jd工厂功能开关.

### ISSUE THREAD

**Issue by ZeroMah** [799953468/Quantumult-X#1]
你好，请问一下如果希望工厂脚本只收集电力，而不投入电力，需要注释脚本哪些位置呢？

**Comment by 799953468** [comment]
现在设计的是电量到选择的商品所需电量时才会注入

**Comment by ZeroMah** [comment]
因为当前选择的商品不是心仪的商品，又不想为它浪费电力，可以选择积攒下来吗

**Comment by 799953468** [comment]
添加了选择,默认是不自动注入  [d872016](https://github.com/799953468/Quantumult-X/commit/d872016345788ccccf90c1767c5a1a4cd74eccf9) @ZeroMah

**Comment by Tersd07** [comment]
@799953468 
`SyntaxError: Identifier 'addEnergy' has already been declared`
`addEnergy` 重复定义，运行出错了。

另外
https://github.com/799953468/Quantumult-X/blob/d872016345788ccccf90c1767c5a1a4cd74eccf9/Scripts/JD/jd_factory.js#L266
这两分数很难刚好相等，建议改成这样：
```js
if (parseInt($.factoryInfo.data.result.factoryInfo.totalScore) <= parseInt($.homeData.data.result.userScore)) {
```

**Comment by 799953468** [comment]
> 这活动很坑的一点是兑换库存不足被视为失败，然后造物机电量会被清空。
> 
> @799953468
> `SyntaxError: Identifier 'addEnergy' has already been declared`
> `addEnergy` 重复定义，运行出错了。
> 
> 另外
> https://github.com/799953468/Quantumult-X/blob/d872016345788ccccf90c1767c5a1a4cd74eccf9/Scripts/JD/jd_factory.js#L266
> 
> 
> 这两分数很难刚好相等，建议改成这样：
> ```js
> if (parseInt($.factoryInfo.data.result.factoryInfo.totalScore) <= parseInt($.homeData.data.result.userScore)) {
> ```

在更新下  已经改了

**Comment by Tersd07** [comment]
> 
> 在更新下 ，已经改了 那个直接大于等于就行了吧 十进制没必要吧

这两个值传过来是字符串，譬如下面的比较会出错。
```js
'4000' <= '10000' // false
```

**Comment by 799953468** [comment]
> > 在更新下 ，已经改了 那个直接大于等于就行了吧 十进制没必要吧
> 
> 这两个值传过来是字符串，譬如下面的比较会不符合预期。
> 
> ```js
> '4000' <= '10000' // false
> ```

可，要不你提个pr吧。我的话要明天改了@Tersd07
