### ISSUE TITLE
增加jdCookie文件

### ISSUE THREAD

**Issue by pmlican** [799953468/Quantumult-X#2]
能不能在同级目录加上./jdCookie.js文件，这样我在自己仓库建yml文件，就可以在actions运行。不然我这边需要clone你的jd_factory.js文件到自己仓库才能运行。谢谢

**Comment by 799953468** [comment]
已添加 [7fe9f62](https://github.com/799953468/Quantumult-X/commit/7fe9f62cdd2c75d8b8bb550bd83fee71764096ca)
