### ISSUE TITLE
jd_paopao.js关注店铺提示系统错误，逛会场没有生效

### ISSUE THREAD

**Issue by ITdesk01** [799953468/Quantumult-X#7]
HI，
我在用jd_paopao.js，发现两个问题

1.逛会场显示成功，但实际没有逛成功
2.关注店铺提示系统错误
![捕获](https://user-images.githubusercontent.com/38835844/100295178-f1fdc380-2fc3-11eb-927c-3c5fd8168280.PNG)
![Screenshot_2020-11-26-08-42-50-999_com jingdong a](https://user-images.githubusercontent.com/38835844/100295183-f3c78700-2fc3-11eb-94de-5d61736f0bd4.jpg)

**Comment by 799953468** [comment]
@ITdesk01 过两天看看   现在再弄其他东西

**Comment by 799953468** [comment]
@ITdesk01 已修复 [475f64d](https://github.com/799953468/Quantumult-X/commit/475f64d213db02439bf45eb30ad1c02e09eb3fd2)

**Comment by ITdesk01** [comment]
> @ITdesk01 已修复 [475f64d](https://github.com/799953468/Quantumult-X/commit/475f64d213db02439bf45eb30ad1c02e09eb3fd2)

辛苦了大佬

**Comment by ITdesk01** [comment]
> @ITdesk01 已修复 [475f64d](https://github.com/799953468/Quantumult-X/commit/475f64d213db02439bf45eb30ad1c02e09eb3fd2)

大佬好像修岔气了，关注是关注成功了，但其他的都不行了
![搜狗截图20201130092744](https://user-images.githubusercontent.com/38835844/100559758-c1cd6200-32ee-11eb-9a5b-c9642987b2b0.png)
![881fde126cb26c72b2db40d15a131c3](https://user-images.githubusercontent.com/38835844/100559779-cd208d80-32ee-11eb-8b1b-8381aff39066.jpg)

**Comment by 799953468** [comment]
@ITdesk01 忘记把注释去掉了😁

**Comment by ITdesk01** [comment]
> @ITdesk01 忘记把注释去掉了😁

辛苦了，我明天试试
